version: "3"

services:
    nginx:
        image: nginx:1.14.2
        container_name: nginx_https_hugoBlog_v1
        volumes:
            - ./etc/nginx:/etc/nginx
            - ./var/log/nginx:/var/log/nginx
            - ./blog.actiger.com:/usr/share/nginx/html
            - /etc/letsencrypt/:/etc/letsencrypt/
        ports:
            - 80:80
            - 443:443

